url: https://catherine.work   # with the https protocol
enforce_ssl: catherine.work   # without any protocol

# General Settings
name: Catherine Smith
job_title: Data Analytics + Web Dev
email: eastandwestwind@gmail.com
description: My expertise is in user behavior analytics and full-stack web development. I enjoy learning new things, being outdoors, and art in all its forms. Also cats.
avatar: /avatar.png
favicon: /avatar.png
twitter_handler: your_handler
analytics_code: UA-64729638-1
disqus: eastandwestwind.disqus.com

# Social Accounts
social_networks:
-  { name: facebook, url: '' }
-  { name: twitter, url: '' }
-  { name: instagram, url: '' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: '' }
-  { name: skype, url: '' }
-  { name: github, url: 'https://github.com/eastandwestwind' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }

# Modules Settings
show_categories: 1
show_tags: 1
show_mood: 0
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: ""
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 100
paginate_path: "/page:num/"

# Conversion
markdown: kramdown

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed